import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
export const codes = { validation: "VALIDATION_FAILED", unavailable: "CALENDAR_UNAVAILABLE", auth: "CALENDAR_AUTH_FAILED", configured: "CALENDAR_NOT_CONFIGURED" } as const;
const allowed = (Deno.env.get("ALLOWED_ORIGINS") ?? "https://quincestone.com").split(",").map((v) => v.trim());
export function cors(req: Request) { const origin = req.headers.get("origin") ?? ""; return { "access-control-allow-origin": allowed.includes(origin) ? origin : allowed[0], "access-control-allow-headers": "authorization, x-client-info, apikey, content-type", "access-control-allow-methods": "POST, OPTIONS", "vary": "Origin" }; }
export function json(req: Request, body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...cors(req), "content-type": "application/json" } }); }
export const fail = (req: Request, code: string, message: string, status = 400) => json(req, { success: false, error: { code, message } }, status);
export function serverClient() { const url = Deno.env.get("SUPABASE_URL"), key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!url || !key) throw new Error("SERVER_NOT_CONFIGURED"); return createClient(url, key, { auth: { persistSession: false } }); }
export async function googleToken() { const id = Deno.env.get("GOOGLE_CLIENT_ID"), secret = Deno.env.get("GOOGLE_CLIENT_SECRET"), refresh = Deno.env.get("GOOGLE_REFRESH_TOKEN"); if (!id || !secret || !refresh) throw new Error("GOOGLE_NOT_CONFIGURED"); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 8000); try { const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", signal: controller.signal, headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: id, client_secret: secret, refresh_token: refresh, grant_type: "refresh_token" }) }); if (!response.ok) throw new Error(response.status === 400 || response.status === 401 ? "GOOGLE_AUTH_FAILED" : "GOOGLE_UNAVAILABLE"); return String((await response.json()).access_token); } finally { clearTimeout(timer); } }
export async function google(path: string, init: RequestInit = {}) { const token = await googleToken(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10000); try { const response = await fetch(`https://www.googleapis.com/calendar/v3${path}`, { ...init, signal: controller.signal, headers: { authorization: `Bearer ${token}`, "content-type": "application/json", ...init.headers } }); if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? "GOOGLE_AUTH_FAILED" : response.status === 429 ? "GOOGLE_RATE_LIMITED" : "GOOGLE_UNAVAILABLE"); return response; } finally { clearTimeout(timer); } }
export function validTimezone(value: string) { try { new Intl.DateTimeFormat("en-US", { timeZone: value }).format(); return value.length <= 100; } catch { return false; } }
export function safeError(error: unknown) { const value = error instanceof Error ? error.message : "UNKNOWN"; if (value === "GOOGLE_NOT_CONFIGURED" || value === "SERVER_NOT_CONFIGURED") return ["CALENDAR_NOT_CONFIGURED", "Live scheduling is not configured.", 503] as const; if (value === "GOOGLE_AUTH_FAILED") return ["CALENDAR_AUTH_FAILED", "Calendar authorization requires attention.", 503] as const; if (value === "GOOGLE_RATE_LIMITED") return ["CALENDAR_RATE_LIMITED", "Scheduling is temporarily busy. Please retry shortly.", 503] as const; return ["CALENDAR_UNAVAILABLE", "Scheduling is temporarily unavailable.", 503] as const; }
export async function audit(event_type: string, status: string, metadata: Record<string, unknown> = {}, error_code?: string) { try { await serverClient().from("integration_events").insert({ provider: "google-calendar", event_type, status, error_code, error_message_safe: error_code ? "Calendar operation failed" : null, metadata }); } catch { /* audit must not expose or replace the primary result */ } }
