import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { App } from "./App";
import "../../../packages/config/src/brand.css";
import "./styles.css";
import "./signature-experience.css";
import "./shop-commerce.css";
import "./commerce-godmode.css";
import "./p13-performance.css";
import "../../../packages/config/src/stability.css";
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);
