import { useEffect, useState } from "react";
import { Link, NavLink, Outlet } from "react-router-dom";
import "../marketing.css";
import "../p2-interaction.css";
import "../web-reconciliation.css";
import "../footer-mobile-architecture.css";
import { CorporateFooter } from "./CorporateFooter";

type Item={label:string;to:string;description:string;external?:boolean};
const platform:Item[]=[{label:"Understand demand",to:"/discover",description:"See what people need before choosing the system."},{label:"Build the experience",to:"/build",description:"Turn understanding into a useful customer path."},{label:"Operate the work",to:"/operate",description:"Route qualified demand through governed operations."},{label:"Learn from outcomes",to:"/scale",description:"Connect action to evidence and improve."}];
const products:Item[]=[{label:"Quincestone Business",to:"/business",description:"Operating infrastructure for authorized workspaces."},{label:"Quincestone Edge",to:"/edge",description:"Understand, qualify and route within business authority."},{label:"Quincestone Shop",to:"https://shop.quincestone.com",description:"Useful products chosen through evidence and utility.",external:true},{label:"Quincestone Account",to:"https://account.quincestone.com",description:"Your identity, profile, orders and saved products.",external:true},{label:"Quincestone Deals",to:"https://QuincestoneDeal.app",description:"Negotiated commerce with explicit authority.",external:true}];
function Logo(){return <span className="corporate-lockup"><img className="brand-logo" src="/quincestone-logo.svg" alt=""/><strong>QUINCESTONE</strong></span>}
function Menu({items,close}:{items:Item[];close:()=>void}){return <div className="nav-popover qs-mega" role="menu">{items.map(item=>item.external?<a key={item.label} href={item.to} role="menuitem" onClick={close}><strong>{item.label}</strong><small>{item.description}</small></a>:<NavLink key={item.label} to={item.to} role="menuitem" onClick={close}><strong>{item.label}</strong><small>{item.description}</small></NavLink>)}</div>}
export function Layout(){const[open,setOpen]=useState<string|null>(null);const[mobile,setMobile]=useState(false);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(null);setMobile(false)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);const close=()=>{setOpen(null);setMobile(false)};return <div className="site-shell corporate-shell"><a className="skip-link" href="#content">Skip to content</a><header className="marketing-header"><Link className="brand" to="/" aria-label="Quincestone home" onClick={close}><Logo/></Link><nav className="marketing-nav" aria-label="Primary navigation"><div className="nav-group"><button className="nav-trigger" aria-expanded={open==="platform"} onClick={()=>setOpen(open==="platform"?null:"platform")}>Platform</button>{open==="platform"&&<Menu items={platform} close={close}/>}</div><NavLink to="/business">Business</NavLink><NavLink to="/edge">Edge</NavLink><a href="https://shop.quincestone.com">Commerce</a><div className="nav-group"><button className="nav-trigger" aria-expanded={open==="company"} onClick={()=>setOpen(open==="company"?null:"company")}>Company</button>{open==="company"&&<Menu items={products} close={close}/>}</div></nav><div className="marketing-actions"><a className="text-link sign-in-link" href="https://account.quincestone.com/sign-in">Sign in</a><NavLink className="button small" to="/assessment">Start assessment</NavLink></div><button className="marketing-menu" aria-label={mobile?"Close menu":"Open menu"} aria-expanded={mobile} aria-controls="mobile-panel" onClick={()=>setMobile(v=>!v)}><span/></button><div id="mobile-panel" className="mobile-panel" data-open={mobile}><strong>ONE QUINCESTONE</strong><NavLink to="/platform" onClick={close}>Platform</NavLink><NavLink to="/business" onClick={close}>Business</NavLink><NavLink to="/edge" onClick={close}>Edge</NavLink><a href="https://shop.quincestone.com">Shop Quincestone</a><a href="https://account.quincestone.com">Account</a><NavLink to="/demo/experience" onClick={close}>See it in action</NavLink><NavLink className="button mobile-cta" to="/assessment" onClick={close}>Start an assessment</NavLink></div></header><main id="content"><Outlet/></main><CorporateFooter/></div>}
