import { Navigate, Route, Routes } from "react-router-dom";
import { ShopLayout } from "./components/ShopLayout";
import { ShopHomeEditorial, ShopStandardPage, ShopFieldNotesPage } from "./pages/ShopEditorialPages";
import { ShopEliteCollection, ShopEliteProduct, ShopEliteSearch, ShopEliteCompare } from "./pages/ShopElite";
import { ShopCartExperience } from "./pages/ShopExperience";

function OrderReturn() { return <section className="shop-status-page"><p className="eyebrow">ORDER RECEIVED</p><h1>Payment confirmation is being reconciled.</h1><p>A browser return is not payment proof. Your order will appear in Account only after the provider result is verified.</p><a className="button" href="https://account.quincestone.com/orders">View orders in Account</a></section>; }
function TruthPage({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="shop-status-page"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></section>; }

export function App() { return <Routes><Route element={<ShopLayout />}><Route index element={<ShopHomeEditorial />} /><Route path="shop" element={<Navigate to="/" replace />} /><Route path="discover" element={<ShopEliteCollection />} /><Route path="featured" element={<ShopEliteCollection />} /><Route path="new" element={<ShopEliteCollection />} /><Route path="collections" element={<ShopEliteCollection />} /><Route path="field-notes" element={<ShopFieldNotesPage />} /><Route path="products" element={<ShopEliteCollection collection="products" />} /><Route path="travel" element={<ShopEliteCollection collection="travel" />} /><Route path="drive" element={<ShopEliteCollection collection="drive" />} /><Route path="companion" element={<ShopEliteCollection collection="companion" />} /><Route path="home-outdoor" element={<ShopEliteCollection collection="home-outdoor" />} /><Route path="product/:slug" element={<ShopEliteProduct />} /><Route path="shop/product/:slug" element={<ShopEliteProduct />} /><Route path="search" element={<ShopEliteSearch />} /><Route path="compare" element={<ShopEliteCompare />} /><Route path="bag" element={<ShopCartExperience />} /><Route path="cart" element={<Navigate to="/bag" replace />} /><Route path="checkout" element={<ShopCartExperience />} /><Route path="order/:orderNumber" element={<OrderReturn />} /><Route path="standard" element={<ShopStandardPage />} /><Route path="shipping" element={<TruthPage eyebrow="SHIPPING" title="Delivery should be evidence-led." text="Availability and timing are shown only from verified fulfillment information." />} /><Route path="returns" element={<TruthPage eyebrow="RETURNS" title="A clear return path is part of the product." text="Returns follow the actual published product and order policy." />} /><Route path="support" element={<TruthPage eyebrow="SUPPORT" title="Help stays close to the transaction." text="Account connects a request to the customer and order context needed to resolve it." />} /><Route path="account" element={<Navigate to="/" replace />} /><Route path="*" element={<TruthPage eyebrow="404 / SHOP" title="This route is outside the product house." text="Return to Shop to continue browsing published products." />} /></Route></Routes>; }
