import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { App } from "./App";
import "../../../packages/config/src/brand.css";
import "./styles.css";
import "./commerce-product.css";
import "./shop-commerce.css";
import "./commerce-godmode.css";
import "./shop-elite.css";
import "./shop-elite-experience.css";
import "./shop-navigation.css";
import "./footer-commerce-premium.css";
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);
