import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type Execution = { id: string; workspace_id: string; action_type: string; provider: string; parameters: Record<string, unknown>; attempt_count: number };
const db = () => { const url = Deno.env.get("SUPABASE_URL"), key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!url || !key) throw new Error("SERVER_NOT_CONFIGURED"); return createClient(url, key, { auth: { persistSession: false } }); };
async function googleToken() { const id=Deno.env.get("GOOGLE_CLIENT_ID"), secret=Deno.env.get("GOOGLE_CLIENT_SECRET"), refresh=Deno.env.get("GOOGLE_REFRESH_TOKEN"); if(!id||!secret||!refresh) throw new Error("GOOGLE_NOT_CONFIGURED"); const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refresh,grant_type:"refresh_token"})}); if(!r.ok) throw new Error(r.status===400||r.status===401?"GOOGLE_AUTH_FAILED":"GOOGLE_UNAVAILABLE"); return String((await r.json()).access_token); }
async function google(path:string,init:RequestInit={}) { const token=await googleToken(); const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),10000); try { const r=await fetch(`https://www.googleapis.com/calendar/v3${path}`,{...init,signal:controller.signal,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...init.headers}}); if(!r.ok) throw new Error(r.status===401||r.status===403?"GOOGLE_AUTH_FAILED":r.status===429?"GOOGLE_RATE_LIMITED":"GOOGLE_UNAVAILABLE"); return r; } finally { clearTimeout(timer); } }
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}})}
function str(v:unknown,max=500){return typeof v==="string"?v.trim().slice(0,max):""}
function retryAt(attempt:number){return new Date(Date.now()+Math.min(3600,15*2**Math.max(0,attempt-1))*1000).toISOString()}
async function run(id:string){ const client=db(); const {data:execution,error}=await client.rpc("claim_action_execution",{target_id:id}); if(error||!execution) throw new Error(error?.message||"ACTION_NOT_CLAIMABLE"); const row=execution as Execution; try { if(row.provider!=="google-calendar"||!["calendar.create","calendar.create_booking","create_calendar_booking"].includes(row.action_type)){const {data,error:e}=await client.rpc("fail_action_execution",{target_id:id,target_status:"failed",target_error_code:"UNSUPPORTED_ACTION",target_error_message:"No executor is registered for this action type and provider.",target_retry_at:null,target_provider_reference:null});if(e)throw new Error("EXECUTION_PERSISTENCE_FAILED");return data;} const p=row.parameters; const calendarId=Deno.env.get("GOOGLE_CALENDAR_ID"); const start=str(p.start??p.startDateTime,80),end=str(p.end??p.endDateTime,80),timezone=str(p.timezone,100); if(!calendarId)throw new Error("GOOGLE_NOT_CONFIGURED"); if(!start||!end||!timezone)throw new Error("INVALID_ACTION_PARAMETERS"); const event={summary:str(p.title,200)||"Quincestone appointment",description:str(p.description,2000)||undefined,start:{dateTime:start,timeZone:timezone},end:{dateTime:end,timeZone:timezone},conferenceData:{createRequest:{requestId:row.id,conferenceSolutionKey:{type:"hangoutsMeet"}}}}; const r=await google(`/calendars/${encodeURIComponent(calendarId)}/events?conferenceDataVersion=1&sendUpdates=none`,{method:"POST",body:JSON.stringify(event)}); const created=await r.json(); if(!created?.id)throw new Error("GOOGLE_UNAVAILABLE"); const result={calendarEventId:String(created.id),meetingUrl:created.hangoutLink??created.conferenceData?.entryPoints?.find((x:{entryPointType:string})=>x.entryPointType==="video")?.uri??null}; const {data,error:e}=await client.rpc("complete_action_execution",{target_id:id,target_provider_reference:String(created.id),target_result:result}); if(e)throw new Error("EXECUTION_PERSISTENCE_FAILED"); return data; } catch(error) { const code=error instanceof Error?error.message:"EXECUTION_FAILED"; const retryable=["GOOGLE_UNAVAILABLE","GOOGLE_RATE_LIMITED","GOOGLE_AUTH_FAILED"].includes(code); const status=code==="GOOGLE_UNAVAILABLE"?"unknown":retryable?"retryable":"failed"; const {data,error:e}=await client.rpc("fail_action_execution",{target_id:id,target_status:status,target_error_code:code.slice(0,128),target_error_message:retryable?"Provider execution did not complete; reconciliation is required before another attempt.":"Action execution failed.",target_retry_at:retryable?retryAt(row.attempt_count):null,target_provider_reference:null}); if(e)throw new Error("EXECUTION_PERSISTENCE_FAILED"); return data; } }
Deno.serve(async(req)=>{if(req.method!=="POST")return response({success:false,error:"Method not allowed"},405);try{const b=await req.json(),id=str(b?.actionExecutionId,80);if(!/^[0-9a-f-]{36}$/i.test(id))return response({success:false,error:"Valid actionExecutionId is required."},400);return response({success:true,execution:await run(id)});}catch(e){return response({success:false,error:e instanceof Error?e.message:"Execution failed."},500);}});
