import { requirePlatformRole } from "@/lib/platform-authority";
import { createCommerceAuthorityClient } from "@/lib/commerce";
import { reviewProductMedia } from "../products/[id]/actions";

export const dynamic = "force-dynamic";
function status(value: unknown) { return typeof value === "string" ? value.toUpperCase().replaceAll("_", " ") : value === true ? "PASSED" : "BLOCKED"; }

export default async function CommerceMediaPage() {
  try { await requirePlatformRole("operator"); } catch { return <main className="main"><div className="content"><div className="eyebrow">COMMERCE / AUTHORITY REQUIRED</div><h1>Media operations are fail-closed.</h1><p className="lede">Sign in with an authorized Quincestone operations identity.</p></div></main>; }
  const supabase = createCommerceAuthorityClient();
  const { data } = await supabase.from("commerce_product_media").select("id,product_id,asset_url,media_type,source,rights_status,verification_status,publication_status,publication_permission,sku_association,sort_order,products:commerce_products(name,slug)").order("created_at", { ascending: false });
  return <main className="main"><div className="content"><div className="header"><div><div className="eyebrow">COMMERCE / MEDIA</div><h1>Media review.</h1><p className="lede">Rights, exact-SKU association, verification and publication are separate decisions. Concept media never becomes verified by accident.</p></div><div className="status"><div className="status-label">Assets</div><div className="status-value">{data?.length ?? 0}</div></div></div><section className="section commerce-table"><div className="section-heading"><div><div className="eyebrow">REVIEW QUEUE</div><h2>Every asset has an explicit state.</h2></div></div>{!data?.length ? <p>No media records exist.</p> : <div className="commerce-product-list">{data.map((asset) => { const product = Array.isArray(asset.products) ? asset.products[0] : asset.products; return <article className="commerce-product-row" key={asset.id}><div><strong>{product?.name || "Unknown product"}</strong><p>{asset.asset_url}</p><small>{status(asset.media_type)} · {status(asset.source)} · rights {status(asset.rights_status)} · verification {status(asset.verification_status)} · publication {status(asset.publication_status)}</small></div><div className="media-actions"><form action={reviewProductMedia.bind(null,asset.product_id,asset.id,"APPROVE")}><button type="submit">Approve</button></form><form action={reviewProductMedia.bind(null,asset.product_id,asset.id,"REJECT")}><button type="submit">Reject</button></form><form action={reviewProductMedia.bind(null,asset.product_id,asset.id,"MARK_CONCEPT")}><button type="submit">Concept</button></form><form action={reviewProductMedia.bind(null,asset.product_id,asset.id,"MARK_VERIFIED")}><button type="submit">Verify</button></form><form action={reviewProductMedia.bind(null,asset.product_id,asset.id,"RESTRICT")}><button type="submit">Restrict</button></form><form action={reviewProductMedia.bind(null,asset.product_id,asset.id,"UNPUBLISH")}><button type="submit">Unpublish</button></form></div></article>; })}</div>}</section></div></main>;
}
