import { Link } from "react-router-dom";

const operatingModel = [["01", "Discover", "Find meaningful demand, clarify the problem, and understand the customer journey."], ["02", "Build", "Turn validated demand into better products, experiences, and systems."], ["03", "Operate", "Move demand through intelligence, transaction, and governed operations."], ["04", "Scale", "Learn from outcomes, improve what works, and expand with control."]];
const business = [["Assessment", "Identify the highest-value customer journey to improve."], ["Structure", "Turn business knowledge, policy, and ownership into an operating foundation."], ["Website", "Build a public experience that moves people toward a useful next action."], ["Edge", "Place intelligence between customer interaction and business operations."], ["Operations", "Create governed workflows, review points, and measurable outcomes."]];
const commerce = [["Demand", "Understand what customers actually want and why."], ["Product Discovery", "Evaluate product opportunities against utility, value, and demand."], ["Validation", "Test carefully before broad catalog or inventory commitments."], ["Sourcing", "Work with reliable supply partners while improving control over time."], ["Shop", "Present real products clearly when a validated commerce surface is ready."], ["Improvement", "Use customer and operational learning to improve the product and experience."]];

export function Home() {
  return <>
    <section className="marketing-hero"><div className="hero-copy"><p className="eyebrow">ONE QUINCESTONE</p><h1>Turn demand into outcomes.</h1><p className="lede">Quincestone is a commerce and operating-systems company. We discover where meaningful demand exists, build better products and experiences around it, and create the systems required to move that demand toward valuable outcomes.</p><div className="actions"><Link className="button" to="/assessment">Get started</Link><Link className="button secondary" to="/platform">Explore the system</Link></div><div className="hero-proof"><span>DEMAND</span><span>EXPERIENCE</span><span>INTELLIGENCE</span><span>TRANSACTION</span><span>OPERATIONS</span></div></div><div className="intelligence-diagram" aria-label="Quincestone operating model"><div className="diagram-label">QUINCESTONE / OPERATING MODEL</div><div className="diagram-flow">{operatingModel.map(([number, label, text]) => <div className="diagram-step" key={number}><b>{number}</b><div><strong>{label.toUpperCase()}</strong><p>{text}</p></div></div>)}</div><div className="diagram-label">UNDERSTAND DEMAND · OPERATE WHAT HAPPENS NEXT · SCALE WHAT WORKS</div></div></section>
    <div className="editorial-band"><div className="editorial-band-inner"><span>DEMAND</span><span>EXPERIENCE</span><span>INTELLIGENCE</span><span>TRANSACTION</span><span>OPERATIONS</span><span>OUTCOME</span><span>LEARNING</span><span>SCALE</span></div></div>
    <section className="architecture-section"><p className="eyebrow">THE PROBLEM</p><div className="section-heading"><h2>Demand is often lost between interest and execution.</h2><p className="section-intro">A customer can discover a business, ask a question, request a quote, browse a product, or start a purchase without the organization having a coherent system for what happens next. Quincestone connects the journey without pretending every step should be automated.</p></div></section>
    <section className="architecture-section" id="system"><p className="eyebrow">THE SYSTEM</p><h2>Discover. Build. Operate. Scale.</h2><div className="pipeline">{operatingModel.map(([number, label, text]) => <div className="pipeline-step" key={number}><span>{number}</span><strong>{label}</strong><p>{text}</p></div>)}</div></section>
    <section className="split-editorial"><div><p className="eyebrow">QUINCESTONE FOR BUSINESS</p><h2>Your website should do more than receive people.</h2><p>Quincestone for Business connects assessment, structure, website, Edge, and operations so a customer journey can move toward a useful outcome with clear authority at every step.</p><div className="grid capability-grid">{business.map(([title, text]) => <article className="panel" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><div className="actions"><Link className="button" to="/assessment">Request an assessment</Link></div></div><div className="dark"><p className="eyebrow">QUINCESTONE COMMERCE</p><h2>Better products. Better value. Built around the customer.</h2><p>Commerce starts with demand and validation, not a random catalog. Supplier-direct fulfillment can be an internal validation mechanism; it is never the public identity of Quincestone.</p><div className="commerce-list">{commerce.map(([title, text]) => <div key={title}><strong>{title}</strong><p>{text}</p></div>)}</div><Link className="button light" to="/shop">Explore commerce</Link></div></section>
    <section className="architecture-section dark-flow"><div className="section-heading"><div><p className="eyebrow">QUINCESTONE EDGE</p><h2>The intelligence layer between customer demand and business operations.</h2></div><p>Edge is not a chatbot. It takes interaction through understanding, collection, qualification, knowledge, policy, routing, action boundaries, human review, outcome, and record.</p></div><div className="flow-grid">{["Interaction", "Understand", "Collect", "Qualify", "Knowledge", "Policy", "Route", "Action", "Human Review", "Outcome", "Record"].map((stage, index) => <article key={stage}><span>{String(index + 1).padStart(2, "0")}</span><h3>{stage}</h3></article>)}</div><div className="actions"><Link className="button light" to="/edge">Explore Edge</Link><Link className="text-link" to="/demo">See the fictional demonstration →</Link></div></section>
    <section className="architecture-section"><p className="eyebrow">HUMAN JUDGMENT</p><div className="section-heading"><h2>Automation where appropriate. Humans where judgment is required.</h2><p className="section-intro">Quincestone keeps authority explicit. Consequential, ambiguous, sensitive, or policy-bound work can stop at a human review boundary rather than being represented as silently executed automation.</p></div></section>
    <section className="architecture-section"><p className="eyebrow">DEMONSTRATION</p><h2>A fictional journey, clearly labeled.</h2><p className="section-intro">Northstone Roofing is a fictional company used to demonstrate the operating model. Demo records are not customer evidence and are never presented as production activity.</p><div className="actions"><Link className="button" to="/demo/experience">Experience the demo</Link><Link className="text-link" to="/demo/operations">Open demo operations →</Link></div></section>
    <section className="product-entry"><div><p className="eyebrow">ASSESSMENT</p><h2>Find the customer journey worth improving first.</h2><p>Start with a focused assessment of demand, experience, intelligence, transaction, and operations. Pricing is confirmed through the assessment path rather than represented by an unverified checkout offer.</p></div><div className="offer-price"><span>QUINCESTONE FOR BUSINESS</span><strong>Assess</strong><small>first</small><Link className="button" to="/assessment">Get started</Link></div></section>
    <section className="architecture-section"><p className="eyebrow">COMPANY PRINCIPLE</p><h2>Understand demand. Operate what happens next. Scale what works.</h2><p className="section-intro">Quincestone is one company expressed through business systems and commerce. The same discipline applies: learn what customers need, create a better experience, govern execution, measure outcomes, and improve from evidence.</p></section>
  </>;
}
