import { useEffect } from "react";
import { Link } from "react-router-dom";

export type LegalPageKind = "privacy" | "terms" | "cookies" | "security";
type Section = { id: string; title: string; text: string; bullets?: string[] };
type Doc = { eyebrow: string; title: string; lead: string; sections: Section[] };
const updated = "September 8, 2026";
const docs: Record<LegalPageKind, Doc> = {
  privacy: { eyebrow: "PRIVACY", title: "Privacy Policy", lead: "Quincestone respects the privacy of people who visit our websites, use our applications, submit information through our forms, interact with demonstrations, or communicate with us. This Policy explains information we may process, why we process it, how it may be shared with service providers, and choices that may be available to you.", sections: [
    {id:"scope",title:"1. Scope",text:"This Policy covers Quincestone public websites and marketing experiences, authenticated applications, forms, assessments, demonstrations, integrations, and direct communications. Third-party services have their own notices."},
    {id:"collect",title:"2. Information We Collect",text:"The categories depend on how you use the service. We aim to collect information relevant to providing, securing, and improving Quincestone."},
    {id:"provided",title:"3. Information You Provide",text:"You may provide information through accounts, forms, assessments, business configuration, or interactions.",bullets:["Name and email address.","Assessment responses, contact messages, and other submissions.","Business name, profile, service areas, hours, services, and operating preferences.","Workflow, knowledge, policy, and integration configuration.","Information included in authorized customer or business interactions."]},
    {id:"automatic",title:"4. Information Collected Automatically",text:"Quincestone may process IP-related security signals, browser or device information, timestamps, diagnostic information, and request or security logs needed to operate and protect the service. Advertising or invasive tracking is not claimed unless actually enabled."},
    {id:"auth",title:"5. Authentication and Account Data",text:"The authenticated application uses session and authentication infrastructure, currently Supabase-based, together with server-side authorization. Account data may include name, email, authentication identifiers, workspace membership, and account status."},
    {id:"workspace",title:"6. Business and Workspace Data",text:"A workspace may contain business profiles, knowledge, policies, workflows, integration records, interactions, operational traces, human-review records, outcomes, and events. Access is intended to remain scoped to the relevant workspace and authorized roles."},
    {id:"demo",title:"7. Demonstration Data",text:"Northstone Roofing is fictional. Public demo routes demonstrate governed intelligence and do not create real Calendar events, payments, CRM records, production workflows, or external messages. Demo text may be processed or temporarily retained where needed for runtime, security, or diagnostics; it is not real customer activity."},
    {id:"payments",title:"8. Payment Information",text:"Quincestone may receive limited transaction information from Stripe, such as payment status and transaction references, when Stripe-hosted checkout is used. Card details entered into Stripe-hosted checkout are handled by Stripe under its own terms and privacy practices. Quincestone does not claim to store complete card numbers."},
    {id:"calendar",title:"9. Calendar and Integration Data",text:"Where authorized, Quincestone may process information needed to check availability, create approved appointments, update or cancel appointments, and maintain integration records. Public demos do not create real Calendar events."},
    {id:"use",title:"10. How We Use Information",text:"Purposes may include providing Quincestone, authentication and workspace access, assessments and inquiries, authorized workflows, operational records, security and abuse prevention, diagnostics, reliability improvement, legal compliance, and agreement enforcement."},
    {id:"basis",title:"11. Legal / Operational Basis for Processing",text:"Depending on jurisdiction and context, processing may be based on providing a requested service or performing an agreement, legitimate operational or security interests, consent where required, or legal obligations. The applicable basis depends on the facts and applicable law."},
    {id:"providers",title:"12. Service Providers",text:"Authorized providers may support hosting, database and authentication, payments, calendar integrations, email, security, and infrastructure. Providers may include Vercel, Supabase, Stripe, Google, and other relevant providers. Their certifications and compliance programs are their own and are not transferred to Quincestone."},
    {id:"retention",title:"13. Data Retention",text:"Information is retained for as long as reasonably necessary to provide the service, maintain security and operational records, satisfy legal obligations, resolve disputes, and enforce agreements. Where practical, information may be deleted or de-identified when no longer needed."},
    {id:"security",title:"14. Data Security",text:"Controls include server-side authorization, workspace-scoped access, row-level authorization where applicable, server-side provider secrets, and governed external side effects. No transmission or storage method is represented as risk-free."},
    {id:"cookies",title:"15. Cookies and Similar Technologies",text:"Essential cookies, local storage, or similar technologies may support authentication, sessions, security, navigation, preferences, and abuse prevention. See the Cookie Policy. Analytics or advertising technologies are not claimed unless actually implemented."},
    {id:"international",title:"16. International Processing",text:"Service providers or infrastructure may process information in countries other than yours. Locations and transfer mechanisms vary by provider and configuration. Where applicable law requires safeguards, Quincestone intends to use the safeguards required for the relevant processing."},
    {id:"rights",title:"17. User Rights and Choices",text:"Depending on location and applicable law, you may have rights to access, correct, delete, restrict, or port personal information, object to certain processing, or withdraw consent where applicable. Rights vary by jurisdiction and may have exceptions."},
    {id:"children",title:"18. Children's Privacy",text:"Quincestone is designed for businesses and professional users and is not intentionally directed to children."},
    {id:"changes",title:"19. Changes to This Policy",text:"We may update this Policy when services, data practices, legal requirements, or security practices change. The dates on this page identify the current version."},
    {id:"contact",title:"20. Contact",text:"Privacy questions or requests can be sent to hello@quincestone.com. Do not send passwords, payment-card numbers, API keys, or other credentials by ordinary email."},
  ]},
  terms: { eyebrow:"TERMS", title:"Terms of Use", lead:"These Terms describe the rules for accessing and using Quincestone websites, applications, demonstrations, assessments, and related services. They are production-oriented terms for the current product model, not jurisdiction-specific legal advice.", sections:[
    {id:"acceptance",title:"1. Acceptance of Terms",text:"By accessing or using Quincestone, you agree to these Terms and applicable product-specific terms. If acting for a business, you represent that you have authority to bind it."},
    {id:"eligibility",title:"2. Eligibility",text:"Quincestone is designed for businesses and professional users. You must be legally able to enter into the applicable agreement and use the service lawfully."},
    {id:"services",title:"3. Quincestone Services",text:"Quincestone provides software and infrastructure designed to help businesses interpret incoming interactions, apply business knowledge and policy, route workflows, and preserve human review where required."},
    {id:"accounts",title:"4. Accounts",text:"You are responsible for account credentials and activity through your account, subject to applicable law. Keep account information sufficiently accurate and report unauthorized access."},
    {id:"acceptable",title:"5. Acceptable Use",text:"You may not use Quincestone for unlawful, fraudulent, abusive, deceptive, or unauthorized activity, or to bypass tenant separation, authorization, policy, human-review controls, or third-party restrictions."},
    {id:"demo",title:"6. Demo Environment",text:"Northstone Roofing is fictional and is not an actual customer. Demo outputs are illustrative and demo routes do not create real appointments, payments, production records, or external workflow actions."},
    {id:"assessment",title:"7. Edge Assessment",text:"The Edge Assessment is a paid assessment/service offering. Its purpose is to identify operating opportunities and practical next steps. It does not guarantee business improvement, revenue, implementation, deployment, or ROI."},
    {id:"payments",title:"8. Payments",text:"Payments may be processed by providers such as Stripe and may be subject to their terms and privacy practices. Quincestone does not guarantee third-party payment availability."},
    {id:"integrations",title:"9. Integrations",text:"Authorized integrations may include calendar or payment infrastructure. Third-party availability, permissions, policies, and data practices remain outside Quincestone's complete control."},
    {id:"data",title:"10. User Content and Business Data",text:"You remain responsible for data and configuration you submit, your policies and customer communications, legal compliance, workflow configuration, authorized actions, account security, and business-information accuracy."},
    {id:"ip",title:"11. Intellectual Property",text:"Quincestone and its licensors retain rights in the service, software, branding, designs, documentation, and proprietary materials except rights expressly granted to you."},
    {id:"feedback",title:"12. Feedback",text:"You may provide feedback to help improve Quincestone. Subject to applicable agreements, Quincestone may use such feedback without an obligation to compensate you."},
    {id:"thirdparty",title:"13. Third-Party Services",text:"Third-party services have separate terms, privacy notices, permissions, fees, and availability. Quincestone does not adopt their certifications or compliance status."},
    {id:"service-changes",title:"14. Service Changes",text:"Quincestone may add, modify, suspend, or discontinue features as the product evolves. Separate contractual commitments control where applicable."},
    {id:"availability",title:"15. Availability",text:"Service interruptions may result from maintenance, provider outages, security events, updates, or circumstances outside Quincestone's reasonable control. No 100% uptime commitment is made here."},
    {id:"security",title:"16. Security Responsibilities",text:"Quincestone maintains service security controls, while users remain responsible for credentials, authorized users, business configuration, and appropriate review of consequential actions."},
    {id:"termination",title:"17. Suspension / Termination",text:"Access may be suspended or terminated when reasonably necessary for security, abuse prevention, legal compliance, non-payment, material breach, or service discontinuation, subject to applicable agreements and law."},
    {id:"disclaimers",title:"18. Disclaimers",text:"Quincestone may assist with interpretation, configured rules, routing, and workflows. Outputs depend on information, configuration, integrations, and system state. Quincestone is not a legal, medical, financial, or other professional advisor merely because it produces an output, and perfect interpretation is not guaranteed."},
    {id:"liability",title:"19. Limitation of Liability",text:"To the extent permitted by law, Quincestone will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages. Nothing excludes liability that cannot lawfully be excluded."},
    {id:"indemnity",title:"20. Indemnity",text:"To the extent permitted by law, users are responsible for claims arising from unlawful use, violation of these Terms, or content and workflows they provide where their responsibility is established. Separate negotiated terms control where applicable."},
    {id:"law",title:"21. Governing Law",text:"Governing law and courts will be determined by the applicable agreement or, where none exists, by law applicable to the contracting relationship. Quincestone does not state a jurisdiction here without verified entity and contracting details."},
    {id:"disputes",title:"22. Dispute Resolution",text:"Before formal proceedings, parties should use hello@quincestone.com to attempt good-faith resolution unless applicable law or another agreement requires a different process."},
    {id:"changes",title:"23. Changes",text:"Quincestone may update these Terms as the service changes. Material changes will be presented through appropriate channels where required."},
    {id:"contact",title:"24. Contact",text:"Questions about these Terms can be sent to hello@quincestone.com. Do not send credentials or payment-card information by ordinary email."},
  ]},
  cookies:{eyebrow:"COOKIES",title:"Cookie Policy",lead:"Quincestone uses browser technologies selectively. This Policy describes technologies that may be necessary for the public website and authenticated product without claiming analytics or advertising systems that are not confirmed active.",sections:[
    {id:"what",title:"1. Cookies and Local Storage",text:"Cookies are small browser values. Local storage and similar technologies can retain information on a device and support sessions, preferences, security, and application behavior."},
    {id:"essential",title:"2. Essential Technologies",text:"Essential browser technologies may support authentication, session continuity, security, navigation, preferences, and fraud or abuse prevention."},
    {id:"session",title:"3. Authentication and Session",text:"The authenticated application may use cookies or related storage to maintain a secure session. These are core application technologies, not advertising tracking."},
    {id:"security",title:"4. Security Technologies",text:"Security-related browser technologies may help recognize valid sessions, reduce abuse, preserve request context, or protect application functionality."},
    {id:"preferences",title:"5. Preferences",text:"Where enabled, browser storage may preserve non-sensitive interface preferences. It is not an authorization grant or customer record."},
    {id:"analytics",title:"6. Analytics",text:"No specific analytics vendor is listed because an active analytics implementation is not confirmed. If analytics is introduced, this Policy should be updated to describe it and applicable controls."},
    {id:"thirdparty",title:"7. Third-Party Technologies",text:"Third-party services may use their own browser technologies under their own policies. Quincestone does not control independent cookie practices on third-party websites."},
    {id:"control",title:"8. Your Controls",text:"Most browsers allow you to review, block, delete, or restrict cookies and local storage. Disabling essential technologies can prevent authentication or core features from working."},
    {id:"updates",title:"9. Updates",text:"We may update this Policy when browser technologies or product functionality changes."},
    {id:"contact",title:"10. Contact",text:"Questions can be sent to hello@quincestone.com."},
  ]},
  security:{eyebrow:"TRUST / SECURITY",title:"Security at Quincestone",lead:"Quincestone is designed around explicit authority boundaries. Interpretation, policy, workflow, and external actions are separated so that understanding an interaction does not automatically authorize an operational side effect.",sections:[
    {id:"identity",title:"Server-authoritative identity",text:"Protected application access is verified server-side. Authentication identifies a principal; authorization determines what that principal may access or change."},
    {id:"tenant",title:"Tenant isolation",text:"Production data is designed around workspace boundaries and row-level authorization. Browser-provided workspace IDs are selectors, not proof of authorization."},
    {id:"policy",title:"Policy before action",text:"Intelligence can interpret an interaction, but interpretation is not authority. Explicit policy and server-side authorization determine whether an operation is permitted."},
    {id:"sideeffects",title:"Side-effect control",text:"External actions use governed server-side paths. The public demo is constrained and cannot create real Calendar events, payments, production CRM records, or external messages."},
    {id:"secrets",title:"Secret separation",text:"Private provider credentials remain server-side. Browser code is not intended to receive service-role keys, payment secrets, OAuth refresh credentials, email API keys, or other private provider credentials."},
    {id:"audit",title:"Auditability",text:"Operational decisions can produce structured traces and durable event records separating observed facts, derived intelligence, policy decisions, proposed actions, human decisions, executed results, and outcomes."},
    {id:"intelligence",title:"The intelligence boundary",text:"Interaction → Interpretation → Knowledge → Policy → Workflow → Human Review → Authorized Action. Policy determines what the system is allowed to do, and human review remains an explicit authority boundary where configured or required. Chain-of-thought and internal prompts are not exposed as a product feature."},
    {id:"providers",title:"Third-party infrastructure",text:"Quincestone may use providers such as Vercel, Supabase, Stripe, and Google for specific infrastructure or integration capabilities. Each provider operates under its own security and compliance program; Quincestone does not inherit provider certifications."},
    {id:"responsible",title:"Responsible use",text:"Security also depends on configuration and human behavior. Workspace administrators remain responsible for users, policies, integration permissions, and review of consequential actions. Quincestone does not represent any system as 100% secure or risk-free."},
    {id:"report",title:"Security reporting",text:"If you believe you found a security issue, use hello@quincestone.com and include non-sensitive detail sufficient to understand the issue. Do not send passwords, private keys, access tokens, or credentials. A dedicated security inbox is not published because its operational availability has not been separately verified."},
    {id:"claims",title:"Public security claims",text:"Quincestone does not currently claim SOC 2, ISO 27001, HIPAA, PCI certification, GDPR certification, regulatory approval, a particular data-residency guarantee, insurance coverage, or a guaranteed breach-response outcome on this page."},
  ]},
};
const links = [["Privacy","/privacy"],["Terms","/terms"],["Cookies","/cookies"],["Security","/security"]] as const;
export function LegalPage({kind}:{kind:LegalPageKind}){
  const page=docs[kind];
  useEffect(()=>{ window.document.title=`${page.title} | Quincestone`; let canonical=window.document.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if(!canonical){canonical=window.document.createElement("link");canonical.rel="canonical";window.document.head.appendChild(canonical);} canonical.href=`https://quincestone.com/${kind}`; let meta=window.document.querySelector<HTMLMetaElement>('meta[name="description"]'); if(!meta){meta=window.document.createElement("meta");meta.name="description";window.document.head.appendChild(meta);} meta.content=page.lead; },[kind,page]);
  return <article className="legal-page"><header className="legal-hero"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p className="legal-lead">{page.lead}</p><div className="legal-meta"><span>Effective {updated}</span><span>Last updated {updated}</span></div></header><div className="legal-layout"><aside className="legal-index" aria-label="On this page"><p>On this page</p>{page.sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title.replace(/^\d+\. /,"")}</a>)}</aside><div className="legal-content">{page.sections.map(s=><section className="legal-section" id={s.id} key={s.id}><h2>{s.title}</h2><p>{s.text}</p>{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}<nav className="legal-crosslinks" aria-label="Legal pages"><span>Quincestone trust & legal</span>{links.map(([label,href])=><Link key={href} to={href}>{label}</Link>)}</nav></div></div></article>;
}
